--- 
abstract: install Digest modules and dependencies
author: Kevin W. Henwood <Khen1950fx@aol.com>
build_requires: 
  Test::More: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Task-Digest
no_index: 
  directory: 
    - inc
    - t
requires: 
  Algorithm::Diff: 0
  Algorithm::GDiffDelta: 0
  Algorithm::RabinKarp: 0
  AutoLoader: 0
  Class::Accessor: 0
  Crypt::Blowfish: 0
  Crypt::Blowfish_PP: 0
  Crypt::CAST5: 0
  Crypt::CBC: 0
  Crypt::CBCeasy: 0
  Crypt::CFB: 0
  Crypt::DES: 0
  Crypt::DES_PP: 0
  Crypt::Eksblowfish: 0
  Crypt::IDEA: 0
  Crypt::OpenSSL::RSA: 0
  Crypt::OpenSSL::Random: 0
  Crypt::RC5: 0
  Crypt::RC6: 0
  Crypt::RIPEMD160: 0
  Crypt::Rijndael: 0
  Crypt::SmbHash: 0
  Crypt::TEA: 0
  Crypt::Twofish2: 0
  Data::Dumper: 0
  Data::OptList: 0
  Digest: 0
  Digest::Adler32: 0
  Digest::BubbleBabble: 0
  Digest::CMAC: 0
  Digest::CRC: 0
  Digest::Crc32: 0
  Digest::DJB: 0
  Digest::DMAC: 0
  Digest::EMAC: 0
  Digest::Elf: 0
  Digest::FNV: 0
  Digest::HMAC: 0
  Digest::Hashcash: 0
  Digest::Haval256: 0
  Digest::JHash: 0
  Digest::MD2: 0
  Digest::MD5: 0
  Digest::MD5::File: 0
  Digest::MD5::M4p: 0
  Digest::ManberHash: 0
  Digest::MultiHash: 0
  Digest::Pearson: 0
  Digest::Pearson::PurePerl: 0
  Digest::Perl::MD4: 0
  Digest::Perl::MD5: 0
  Digest::SHA: 0
  Digest::SHA1: 0
  Digest::SHA2: 0
  Digest::SV1: 0
  Digest::Tiger: 0
  Digest::TransformPath: 0
  Digest::Whirlpool: 0
  File::Find::Rule: 0
  File::Spec: 0
  File::Stat::Bits: 0
  File::Temp: 0
  Filter::Simple: 0
  Getopt::Long: 0
  LWP::UserAgent: 0
  MD5: 0
  MIME::Base32: 0
  MIME::Base64: 0
  MIME::Base64::Perl: 0
  Params::Util: 0
  Perl::Critic: 0
  Pod::Usage: 0
  RIPEMD160: 0
  SHA: 0
  Smart::Comments: 0
  Storable: 0
  String::CRC: 0
  String::CRC32: 0
  Sub::Exporter: 0
  Sub::Install: 0
  Test::Exception: 0
  Test::More: 0
  Test::use::ok: 0
  Text::Balanced: 0
  Text::Tabs: 0
  Time::Local: 0
  UNIVERSAL::can: 0
  XSLoader: 0
  bignum: 0
  perl: 5.6.0
  version: 0
version: 0.01
